LENGTH:12
START_ADD:DEV_OUT_START_ADD

VAR LOW_BOUND
VAR MIN_IDX
VAR TEMP
VAR I
VAR ADJ_LENGTH

// Preload with random values
DEV_OUT_0 := 67
DEV_OUT_1 := 24
DEV_OUT_2 := 93
DEV_OUT_3 := 20
DEV_OUT_4 := 10
DEV_OUT_5 := 39
DEV_OUT_6 := 12
DEV_OUT_7 := 88
DEV_OUT_8 := 91
DEV_OUT_9 := 79
DEV_OUT_10 := 49
DEV_OUT_11 := 19

// Necessary since we're working with memory indexes
// Could subtract START_ADD from counters instead but this is cheaper
ADJ_LENGTH := LENGTH + START_ADD
LOW_BOUND := START_ADD
(ASSIGNMENT_LOOP)
    MIN_IDX := LOW_BOUND
    I := LOW_BOUND + 1

    (COMPARISON_LOOP)
        M[MIN_IDX]; IF <= M[I] JMP END_CHANGE_MIN_IF
            MIN_IDX := I
        (END_CHANGE_MIN_IF)

        I := I + 1
        ADJ_LENGTH - I; IF != 0 JMP COMPARISON_LOOP
    // END COMPARISON LOOP

    TEMP := M[LOW_BOUND]
    M[LOW_BOUND] := M[MIN_IDX]
    M[MIN_IDX] := TEMP

    LOW_BOUND := LOW_BOUND + 1
    ADJ_LENGTH - LOW_BOUND; IF == 1 JMP END
    1; JMP ASSIGNMENT_LOOP
// END ASSIGNMENT LOOP

(END)
1; JMP END